// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_application is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/micheltank/eth-fee-calculator/internal/domain"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetTransactionsPerHour mocks base method.
func (m *MockRepository) GetTransactionsPerHour(from, to int64, page int) ([]domain.TransactionCostPerHour, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsPerHour", from, to, page)
	ret0, _ := ret[0].([]domain.TransactionCostPerHour)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsPerHour indicates an expected call of GetTransactionsPerHour.
func (mr *MockRepositoryMockRecorder) GetTransactionsPerHour(from, to, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsPerHour", reflect.TypeOf((*MockRepository)(nil).GetTransactionsPerHour), from, to, page)
}
